#!/bin/bash
# simple TORQUE/PBS job script to run program my_prog 

# set default resource requirements for job
# - these can be overridden on the qsub command line (this is for a 4hour job)
#PBS -l walltime=15:00:00

# Change to directory from which job was submitted.
# (The actual name is held in the PBS environment variable $PBS_O_WORKDIR)
cd $PBS_O_WORKDIR

# Run my_prog taking input from file inputfile and sending output to outputfile -l nodes=1,ncpus=1
###2 Reps

COUNTER=2
  while [  $COUNTER -lt 20 ]; do
          echo The counter is $COUNTER

	qsub -v theta=$COUNTER,trials=1000000,NSize=100,model=synapseSingleFilterUnifiedWithDecay MFPT.job
	qsub -v theta=$COUNTER,trials=100000,NSize=1000,model=synapseSingleFilterUnifiedWithDecay MFPT.job
	qsub -v theta=$COUNTER,trials=10000,NSize=10000,model=synapseSingleFilterUnifiedWithDecay MFPT.job
	qsub -v theta=$COUNTER,trials=1000,NSize=100000,model=synapseSingleFilterUnifiedWithDecay MFPT.job
	qsub -v theta=$COUNTER,trials=1000,NSize=1000000,model=synapseSingleFilterUnifiedWithDecay MFPT-long.job
          let COUNTER=COUNTER+1 
  done



